apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.appName }}-client
  labels:
    {{- toYaml .Values.commonLabels | nindent 4 }}
  annotations:
    # https://docs.openshift.com/container-platform/4.7/networking/routes/route-configuration.html
    haproxy.router.openshift.io/hsts_header: max-age=31536000;includeSubDomains;preload
spec:
  path: /
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: {{ .Values.serverServiceName }}
    weight: 100

  wildcardPolicy: None
