apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serverServiceName }}
  labels:
    {{- toYaml .Values.commonLabels | nindent 4 }}
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: console-serving-cert
spec:
    type: ClusterIP
    selector:
      {{- toYaml .Values.commonLabels | nindent 6 }}
    ports:
    - port: 80
      name: {{ .Values.serverHttpPortName }}
      targetPort: {{ .Values.serverHttpPort }}
      protocol: TCP
    - port: 443
      name: {{ .Values.serverHttpsPortName }}
      targetPort: {{ .Values.serverHttpsPort }}
      protocol: TCP
