appName: github-connector
namespace: github-connector

# REQUIRED VALUE
# oc whoami --show-server
# https://github.com/helm/helm/issues/2055
clusterApiServer: "https://api.crc.testing:6443"

# REQUIRED VALUE:
# This is the apps.<cluster url> subdomain.which may have been edited by the admin. There does not appear to be a user API to get this.
# the easiest way to get this is to `oc expose <some service>` and then look at its subdomai
# or look at the console URL, after the first '.' in the domain name.
clusterAppsSubdomain: "apps-crc.testing"

# Use the tpl function to access these values
# https://stackoverflow.com/a/62896363
subdomainCheck: '{{- required ".Values.clusterAppsSubdomain must be set. Refer to the values.yaml" .Values.clusterAppsSubdomain }}'
appHost: '{{- printf "%s.%s" .Values.appName .Values.clusterAppsSubdomain }}'
appUrl: '{{- printf "https://%s" (tpl .Values.appHost .) }}'

################################################################################

serviceAccountName: github-connector
# A rolebinding is created with this role, allowing the application pod to
# modify resources in the namespace
serviceAccountRole: edit

################################################################################

secretName: github-connector

sessionSecretKeyName: session-secret
sessionStoreKeyName: session-store-secret

oauthClientId: github-connector-oauth-client
oauthClientSecretKeyName: oauth-secret
# URL path must match the route used in the server code.
oauthCallbackUrl: '{{- printf "%s/api/v1/auth/callback" (tpl .Values.appUrl .) }}'

servingCertSecret: connector-serving-cert
servingCADirectory: /var/certs/serving
oauthCADirectory: /var/certs/secrets/oauth
apiserverCADirectory: /var/certs/secrets/apiserver
# insecureTrustApiServerCert: false

################################################################################

commonLabels:
  app: openshift-github-connector

deploymentLabels:

################################################################################

serverReplicaCount: 1
readOnlyRootFilesystem: true

serverImage: quay.io/tetchell/openshift-github-connector
serverTag: latest

serviceName: github-connector
serverHttpPort: 3003
serverHttpPortName: server-http
serverHttpsPort: 3443
serverHttpsPortName: server-https
