apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.commonLabels | nindent 4 }}
  annotations:
    # https://docs.openshift.com/container-platform/4.7/networking/routes/route-configuration.html
    haproxy.router.openshift.io/hsts_header: max-age=31536000;includeSubDomains;preload
spec:
  {{ $subdomainCheck := tpl .Values.subdomainCheck . }}
  host: {{ tpl .Values.appHost . | quote }}
  port:
    targetPort: {{ .Values.serverHttpsPort }}
  path: /
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: {{ .Values.serviceName }}
    weight: 100

  wildcardPolicy: None
