# https://docs.openshift.com/container-platform/4.7/authentication/configuring-oauth-clients.html
# https://docs.openshift.com/container-platform/4.7/authentication/configuring-internal-oauth.html
apiVersion: oauth.openshift.io/v1
kind: OAuthClient
metadata:
  name: {{ .Values.oauthClientId }}
  labels:
    {{- toYaml .Values.commonLabels | nindent 4 }}
{{ $oauthSecret := uuidv4 | b64enc }}
secret: {{ $oauthSecret }}
redirectURIs:
  - {{ tpl .Values.oauthCallbackUrl . | quote }}
grantMethod: auto

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.commonLabels | nindent 4 }}
type: Opaque
data:
  {{ .Values.oauthClientSecretKeyName }}: {{ $oauthSecret | b64enc }}
  {{ .Values.sessionSecretKeyName }}: {{ uuidv4 | b64enc }}
  {{ .Values.sessionStoreKeyName }}: {{ uuidv4 | b64enc }}
