name: Build and run
on:
  push:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Increase max watches
        run: |
          set -ex
          echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
          sudo sysctl -p

      - uses: actions/checkout@v2

      - uses: bahmutov/npm-install@v1

      - name: Lint
        run: |
          yarn lint

      - name: Build
        run: |
          yarn build

      - name: Run dev
        shell: bash
        run: |
          set -eEx
          nohup yarn dev:all > out.log 2>&1 &
          dev_pid=$!
          echo "dev_pid=$dev_pid" >> $GITHUB_ENV

          yarn wait-on -l tcp:3000 -t 60000
          yarn wait-on -l tcp:3003 -t 60000

      - name: Test
        shell: bash
        run: |
          set -eEx
          curl -sSf http://localhost:3000
          curl -sSf http://localhost:3003

      - name: Stop
        if: always()
        run: |
          kill $dev_pid

      - name: Print output
        if: always()
        run: |
          cat out.log
