name: Build and run
on:
  push:

env:
  PORT: 3000
  OAUTH_CLIENT_SECRET: "stub"
  SESSION_SECRET: "stub"
  SESSION_STORE_SECRET: "stub"

jobs:
  ci:
    name: CI
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Increase max watches
        run: |
          set -ex
          echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
          sudo sysctl -p

      - uses: actions/checkout@v2

      - uses: bahmutov/npm-install@v1

      - name: Lint
        run: |
          yarn lint

      - name: Build
        run: |
          yarn build

      - uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}

      - uses: tetchel/generate-tls-cert@v1
        with:
          output_directory: /var/certs/localhost

      - name: Add cert to env configuration
        run: echo "SERVING_CA_DIRECTORY=/var/certs/localhost" >> .env.local

      - name: Run dev
        shell: bash
        run: |
          set -eEx
          nohup yarn dev:all > out.log 2>&1 &
          dev_pid=$!
          echo "dev_pid=$dev_pid" >> $GITHUB_ENV

          yarn wait-on -l tcp:${{ env.PORT }} -t 60000

      - name: Test
        shell: bash
        run: |
          set -eEx
          curl -sSfk https://localhost:${{ env.PORT }}

          # Broken because the server crashes due to no OpenShift cluster.
          # curl -sSfk https://localhost:${{ env.PORT }}/api/v1/

      - name: Stop
        if: always()
        run: |
          kill $dev_pid

      - name: Print output
        if: always()
        run: |
          cat out.log
